### ISSUE TITLE
Time period plots

### ISSUE THREAD

**Issue by Doubletop12** [evilbunny2008/sensibo-python-sdk#4] opened 2024-02-06 21:43 UTC
The addition of time period plots is great. However, I do not having any data beyond the last month and this results in a very strange display, especially for the year display. The time period of the graph is set to the period that there is data for but there are only about 10 data points. Maybe the timeframe should be set to the period selected and any missing data points not plotted?

Switching day -> week -> day -> month -> day works but when the transition to year is made it takes a long time to render the data and again  to return to the day display. 

![Capture09](https://github.com/evilbunny2008/sensibo-python-sdk/assets/60131475/c1192930-0a0d-48ae-97cd-4576667fb590)

**Comment by Doubletop12** [comment] 2024-02-06 21:46
(just noticed that the Y axis values are missing and eventally the x axis points were rendered.)
![Capture10](https://github.com/evilbunny2008/sensibo-python-sdk/assets/60131475/6a2cdfa1-d2e1-4ac9-a87f-810838050520)

**Comment by evilbunny2008** [comment] 2024-02-07 10:24
I'm still working on this, and the year display chews up a lot of CPU time/memory, so I'm trying to come up with a better solution.

Not sure what's happening with the Y axis labels as I'm not able to reproduce it.

**Comment by evilbunny2008** [comment] 2024-02-07 13:23
This should be fixed along with a few other bugs in commit 7479da9

**Closed** 2024-02-07 13:24 UTC

**Comment by evilbunny2008** [comment] 2024-02-08 12:22
Just a follow up, yearly graphs are now rendering properly and quickly even on low end hardware
